---
- name: example to using idempotent in playbook
  hosts: all
  tasks:
    - name: BLOCO 1
      shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf

    - name: BLOCO 2
      copy:
        content: "nameserver 8.8.8.8"
        dest: /etc/resolv.conf
...


