---
  - hosts: localhost
    tasks:
    - name: "create directory"
      file:
       path: /home/user1
       state: touch
      with_items:
       - arq1.txt
       - arq2.txt

    - name: " Inserting text in files "
      lineinfile:
       path: /home/{{item}}
       state: present
       line: 'Add text in the file'
      with_items:
        - arq1.txt
        - arq2.txt
        
