disk:
 - size_gb: 37
   type: thin
   datastore: "{{ datastore }}"
   autoselect_datastore: True
 - size_gb: 160
   type: thin
   datastore: "{{ datastore }}"
   autoselect_datastore: True
 - size_gb: 289
   type: thin
   datastore: "{{ datastore }}"
   autoselect_datastore: True
 - size_gb: 577
   type: thin
   datastore: "{{ datastore }}"
   autoselect_datastore: True
 - size_gb: 37
   type: thin
   datastore: "{{ datastore }}"
   autoselect_datastore: True
 - size_gb: 150
   type: thin
   datastore: "{{ datastore }}"
   autoselect_datastore: True
