- name: remove the ca consumer of server
  command: yum erase 'katello-ca-consumer-*' -y 
  ignore_errors: yes

- name: copy /etc/rhsm.conf
  copy:
    src: /etc/rhsm/rhsm.conf
    dest: /etc/rhsm/rhsm.conf.bkp

- name: unregister and clean repos
  command: subscription-manager clean 

- name: download katello ca consumer
  get_url: 
    url: http://{{ foreman_server }}/pub/katello-ca-consumer-latest.noarch.rpm
    dest: /tmp/katello-ca-consumer-latest.noarch.rpm

- name: install katello agent
  command: yum localinstall /tmp/katello-ca-consumer-latest.noarch.rpm -y

- name: register and subscribe
  redhat_subscription:
#    activationkey: '{{ activation_key }}'
    org_id: '{{ org_id }}'
    force_register: yes
    server_insecure: yes
    state: present
  register: task_result
  until: task_result.stdout.find("System successfully registered to") != -1
  #retries: 5
  #delay: 60

- name: update katello-agentt
  yum:
    name: katello-agent
    state: latest
