- name: remove the ca consumer of server
  command: yum erase 'katello-ca-consumer-*' -y
  ignore_errors: yes

- name: copy /etc/rhsm.conf
  copy:
    src: /etc/rhsm/rhsm.conf
    dest: /etc/rhsm/rhsm.conf.bkp

- name: unregister and clean repos
  command: subscription-manager clean

- name: download katello ca consumer PROD
  get_url:
    url: '{{ foreman_server }}/pub/katello-ca-consumer-latest.noarch.rpm'
    validate_certs: no
    dest: /tmp/katello-ca-consumer-latest.noarch.rpm

- name: install katello agent
  command: yum localinstall /tmp/katello-ca-consumer-latest.noarch.rpm -y

- name: register and subscribe
  redhat_subscription:
    activationkey: '{{ activation_key }}'
    org_id: '{{ org_id }}'
    username: '{{ username_foreman }}'
    password: '{{ password_foreman }}'
    force_register: yes
    server_insecure: yes
    state: present
  register: task_result
  
- name: subscription machine in the foreman
  command: subscription-manager register --org="Topazio" --activationkey="ak_centos7" --force

- name: update katello-agentt
  yum:
    name: katello-agent
    state: latest
